### ISSUE TITLE
BEL JGF 3.0: Alignment of evidence format to support BEL Nanopubs.

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/bel_parser#12]
JGF

Background

The [BEL JGF 2.0 schema](http://jsongraphformat.info/child-schemas/bel-json-graph-2.0.schema.json) represents a BEL node-edge graph with nanopubs as edge metadata. A revision to this schema will align it with our nanopub definition.

Tasks

**Required**
- [x] Add graph metadata for BEL version.

**Nice to Have**
- [x] Rename evidence to nanopub.
- [x] Align nanopub schema with [JSON evidence schema](http://next.belframework.org/schemas/evidence.schema.json). The JSON evidence used in the OpenBEL API includes complete schema for a Nanopub.
- [x] Add URI support for BEL namespace and annotation in the *nanopub.references* schema.

**Comment by wshayes** [comment]
@abargnesi  Are the two required items the same thing?

**Comment by abargnesi** [comment]
Yeah woops. Fixed.

**Comment by wshayes** [comment]
No checkmarks - can't see my progress :(  

:)
