### ISSUE TITLE
BEL RDF 2.0: Design and implement RDF schema for BEL, version 2.0.

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/bel_parser#13]
Background

An RDF representation is needed for BEL, version 2.0. This work should include design, documentation, and RDF schema triples (*rdfs*) required to encode BEL, version 2.0 concepts as triples.

Tasks

- Design RDF model for BEL, version 2.0 constructs.
  - [ ] Variants
  - [ ] Protein cleavage fragments
  - [ ] Post-translational protein modifications
  - [ ] Translocations and cellular locations
  - [ ] Activity functions
  - [ ] Regulates relationship
  - Nanopub enhancements
    - [ ] "Evidence" annotation renamed to "Support"
    - [ ] Revisit supporting annotation domain (e.g. Anatomy) that comprise multiple datasets (e.g. MESH, UBERON). See [conversation](http://wiki.openbel.org/display/~abargnesi/Resolving+annotations+and+namespaces+by+type+URI) with @ncatlett.
- bel.rb
  - [ ] RDF translator support.

Open questions

- Do we encode BEL version at the nanopub level to enable reasoning across BEL, version 1.0 and 2.0?

**Comment by abargnesi** [comment]
Schema design estimate: 3 days (April 4th, end of day).

**Comment by wshayes** [comment]
https://github.com/OpenBEL/language/commit/b130160028b9dd0ceb9b8f4f1eba90a2954bac47
