### ISSUE TITLE
Update BELMgr to use /api/relationships

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/bel_parser#46]

**Comment by abargnesi** [comment]
Can we name the route /api/relationship for consistency with the BEL specification?

**Comment by wshayes** [comment]
yes

**Comment by wshayes** [comment]
Looks like the rest of the api uses the plural form - so I've updated the name to /api/relationships

**Comment by wshayes** [comment]
I've partially added the /api/relationships route.  Waiting on a response for https://waffle.io/OpenBEL/bel_parser/cards/572386c9d39509b000f2b31b
