### ISSUE TITLE
Normalize Demo, Dev and Production servers

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/bel_parser#50]
Proposing:

demo.openbel.org should be a landing page that has a link to belmgr, apidocs, openbelapi (and any other services available to demo by openbel).  the links to each service can be either subdomains or paths off of demo.openbel.org (same for dev.openbel.org below))

dev.openbel.org should be a landing page that has all of the endpoints for the dev version of the belmgr, openbelapi, apidocs, etc

openbel.org should be the landing page for openbel and point to the other resources as a high level guide

api.openbel.org should be the public production endpoint for the openbel api

apidocs.openbel.org should be the public production endpoint for the openbel api - in case we decide to use a hosting service for this

auth.openbel.org (or users.openbel.org) for the authentication endpoint

belmgr.openbel.org should be the public production belmgr instance

We'll retire the belframework.org domain completely.

For the internal Selventa installation of openbel tools/services - belmgr.selventa.com, openbel.selventa.com(/api?) - apidocs hosted on public server and linked from top-level api entrypoint.

**Comment by nbargnesi** [comment]
I like identity.openbel.org in place of auth.openbel.org. All the others look good.

**Comment by abargnesi** [comment]
Change apidocs.openbel.org to docs.openbel.org. The docs.openbel.org site should disseminate all documentation.

**Comment by abargnesi** [comment]
Synonyms for demo.openbel.org:
- try.openbel.org
- play.openbel.org

**Comment by abargnesi** [comment]
Maybe also blog.openbel.org.

**Comment by wshayes** [comment]
Closing this issue in order to consolidate this at openbel/openbel.github.io#5
