### ISSUE TITLE
String does not yield incomplete AST if starting with non-quote.

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/bel_parser#66]
A string that does not start with a double quote character will result in nothing. We may
want to return an incomplete string AST with an empty value in this case.

Example:
```bash
[tony@starship bel_parser]$ rlwrap ruby -I lib lib/bel_parser/parsers/common/string.rb
AKT"1"
(no result; string action code was never called)
```

**Comment by nbargnesi** [comment]
This has [the following side effect](https://github.com/OpenBEL/bel_parser/commit/f003d5b7480f90cd2ebc3faa48b3a42534b07ac0#diff-31f05b8e385b486d9d0a616083403f6eR17) that I don't particularly like. It widens the input the parser is willing to process. Contrast this with [the list machine instantiation](https://github.com/OpenBEL/bel_parser/blob/master/lib/bel_parser/parsers/common/list.rl#L124) which will only parse input that starts like a list.

The two are inconsistent. We should either allow all input and implement error states everywhere or only parse input that looks like it's applicable to our machine's domain (i.e., '{' in the list machine).

I don't think this needs to be done at the moment. Our test-first approach will suffice for the time being.
