### ISSUE TITLE
Can't upload BEL Script in BELMgr

### ISSUE THREAD

**Issue by wshayes** [OpenBEL/bel_parser#72]
Getting a 500 error from the OpenBEL API

 /api/datasets HTTP/1.0" 200 - 0.0100
May 27 17:36:17 openbel supervisord: openbelapi /opt/jruby/gems/gems/bel_parser-1.0.0.alpha.52-java/lib/bel_parser/resource/resource_url_reader.rb:26: warning: already initialized constant DEFAULT_RESOURCE_VALUE_DELIMITER
May 27 17:36:17 openbel supervisord: openbelapi /opt/jruby/gems/gems/bel-1.0.0.beta.1/lib/bel/quoting.rb:22: warning: already initialized constant Keywords
May 27 17:36:17 openbel supervisord: openbelapi /opt/jruby/gems/gems/bel-1.0.0.beta.1/lib/bel/quoting.rb:25: warning: already initialized constant KeywordMatcher
May 27 17:36:17 openbel supervisord: openbelapi /opt/jruby/gems/gems/bel-1.0.0.beta.1/lib/bel/quoting.rb:28: warning: already initialized constant NonWordMatcher
May 27 17:36:17 openbel supervisord: openbelapi /opt/jruby/gems/gems/bel-1.0.0.beta.1/lib/bel/quoting.rb:32: warning: already initialized constant StrictQuotedMatcher
May 27 17:36:17 openbel supervisord: openbelapi /opt/jruby/gems/gems/bel-1.0.0.beta.1/lib/bel/quoting.rb:36: warning: already initialized constant LenientQuotedMatcher
May 27 17:36:17 openbel supervisord: openbelapi /opt/jruby/gems/gems/bel-1.0.0.beta.1/lib/bel/quoting.rb:39: warning: already initialized constant QuoteNotEscapedMatcher
May 27 17:36:36 openbel kernel: [11472.344961] hrtimer: interrupt took 4555737 ns
May 27 17:36:40 openbel supervisord: openbelapi 2016-05-27 21:36:40 - NoMethodError - undefined method `string_literal' for #<String:0x6dc3083a>:

**Comment by abargnesi** [comment]
This particular error is fixed.

FYI, currently only URI resources (e.g. BEL Annotation and Namespace URIs) work for dataset import. OpenBEL/openbel-api#111 is still open regarding file-locking of mapdb3.

**Comment by abargnesi** [comment]
Here is an example of BEL Script with URIs.

[small_corpus_uris.zip](https://github.com/OpenBEL/bel_parser/files/287432/small_corpus_uris.zip)
